// lib/checks/patterns.ts

export const PATTERNS = {
  // Empty/invalid href patterns (NOT including # - anchor links are valid!)
  EMPTY_HREFS: [
    '',
    'javascript:void(0)',
    'javascript:void(0);',
    'javascript:;',
    'javascript:',
    'about:blank',
  ],

  // Generic anchor texts (English + Georgian)
  GENERIC_ANCHORS: [
    'click here',
    'read more',
    'here',
    'learn more',
    'more',
    'link',
    'this',
    'click',
    'go',
    'see more',
    'view more',
    'continue',
    'details',
    'info',
    'more info',
    'find out more',
    'discover more',
    'see all',
    'view all',
    'download',
    'start',
    'submit',
    'next',
    'previous',
    'back',
    'go back',
    // Georgian
    'წაიკითხეთ მეტი',
    'მეტი',
    'აქ',
    'ვრცლად',
    'დეტალები',
    'გაგრძელება',
    'იხილეთ',
    'ნახეთ',
    'გადასვლა',
    'სრულად',
    'დაწვრილებით',
  ],

  // AI content detection phrases
  AI_PHRASES: [
    'delve into',
    'delve deeper',
    'dive into',
    'dive deeper',
    'it is important to note',
    'it is worth noting',
    'it is crucial to',
    'in conclusion',
    'to summarize',
    'in summary',
    'moreover',
    'furthermore',
    'additionally',
    'consequently',
    'leverage',
    'utilize',
    'facilitate',
    'implement',
    "in today's digital landscape",
    "in today's world",
    'in this day and age',
    'game-changer',
    'game changer',
    'cutting-edge',
    'cutting edge',
    'unlock the potential',
    'unlock your potential',
    'unleash',
    'seamlessly',
    'effortlessly',
    'streamline',
    'comprehensive guide',
    'ultimate guide',
    'complete guide',
    'crucial aspect',
    'key aspect',
    'important aspect',
    'plays a vital role',
    'plays a crucial role',
    'plays an important role',
    'embark on',
    'embark upon',
    'navigate the complexities',
    'navigate through',
    'holistic approach',
    'robust',
    'scalable',
    'empower',
    'synergy',
    'paradigm',
    'ecosystem',
    'landscape',
    'harness',
    'revolutionize',
    'transform',
    'elevate',
    'optimize',
    'maximize',
    'amplify',
    'supercharge',
    'turbocharge',
    'skyrocket',
    'unleash the power',
    'tap into',
    'take your .* to the next level',
    'at the end of the day',
    'when it comes to',
    'in the realm of',
    'in the world of',
    'needless to say',
    'it goes without saying',
    'rest assured',
    'without a doubt',
    'first and foremost',
    'last but not least',
    'at the core of',
    'at the heart of',
    'as a matter of fact',
  ],

  // CMS detection patterns
  CMS: [
    { name: 'WordPress', patterns: ['wp-content', 'wp-includes', 'wp-json', '/wp-admin', 'wordpress'] },
    { name: 'Shopify', patterns: ['shopify', 'cdn.shopify', 'myshopify.com'] },
    { name: 'Wix', patterns: ['wix.com', 'wixstatic', 'parastorage.com', '_wix_browser_sess'] },
    { name: 'Squarespace', patterns: ['squarespace', 'sqsp.net', 'static1.squarespace'] },
    { name: 'Webflow', patterns: ['webflow', 'assets.website-files.com'] },
    { name: 'Drupal', patterns: ['drupal', '/sites/default/files', 'drupal.settings'] },
    { name: 'Joomla', patterns: ['joomla', '/media/system/js', 'com_content'] },
    { name: 'Magento', patterns: ['magento', 'mage/', 'requirejs/require', 'mage-init'] },
    { name: 'PrestaShop', patterns: ['prestashop', '/modules/ps_'] },
    { name: 'BigCommerce', patterns: ['bigcommerce', 'cdn11.bigcommerce'] },
    { name: 'Ghost', patterns: ['ghost', 'ghost-url', 'ghost/api'] },
    { name: 'HubSpot', patterns: ['hubspot', 'hs-scripts.com', 'hubspotusercontent', 'hscollectedforms'] },
    { name: 'Contentful', patterns: ['contentful', 'ctfassets.net'] },
    { name: 'Sanity', patterns: ['sanity.io', 'cdn.sanity.io'] },
    { name: 'Tilda', patterns: ['tilda', 'tildacdn.com'] },
    { name: 'Blogger', patterns: ['blogger.com', 'blogspot.com'] },
    { name: 'Medium', patterns: ['medium.com', 'cdn-images-1.medium.com'] },
    { name: 'Weebly', patterns: ['weebly.com', 'editmysite.com'] },
    { name: 'Jimdo', patterns: ['jimdo', 'jimdofree.com'] },
    { name: 'Woocommerce', patterns: ['woocommerce', 'wc-ajax'] },
    { name: 'OpenCart', patterns: ['opencart', 'route=common'] },
    { name: 'TYPO3', patterns: ['typo3', 'typo3conf'] },
    { name: 'Craft CMS', patterns: ['craftcms', 'craft'] },
    { name: 'Strapi', patterns: ['strapi', '/api/'] },
    { name: 'Prismic', patterns: ['prismic', 'prismic.io'] },
    { name: 'DatoCMS', patterns: ['datocms', 'dato-cms'] },
    { name: 'Storyblok', patterns: ['storyblok', 'storyblok.com'] },
  ],

  // Framework detection patterns
  FRAMEWORKS: [
    { name: 'Next.js', patterns: ['__next', '_next/static', '__next_data__', 'next/dist', '__NEXT_DATA__'] },
    { name: 'Nuxt.js', patterns: ['__nuxt', '_nuxt/', 'nuxt', 'nuxtjs', '__NUXT__'] },
    { name: 'Gatsby', patterns: ['gatsby', '___gatsby', 'gatsby-image', 'gatsby-resp-image'] },
    { name: 'React', patterns: ['react-root', '_reactroot', 'data-reactid', 'data-reactroot', '__REACT_DEVTOOLS'] },
    { name: 'Vue.js', patterns: ['data-v-', '__vue__', 'vue-router', 'vuex', '__VUE__'] },
    { name: 'Angular', patterns: ['ng-version', 'ng-app', '_ngcontent', 'angular', 'ng-reflect'] },
    { name: 'Svelte', patterns: ['svelte', '__svelte', 'svelte-'] },
    { name: 'SvelteKit', patterns: ['sveltekit', '__sveltekit'] },
    { name: 'Astro', patterns: ['astro', 'astro-island', 'data-astro'] },
    { name: 'Remix', patterns: ['remix', '__remix'] },
    { name: 'Ember', patterns: ['ember', 'data-ember'] },
    { name: 'Laravel', patterns: ['laravel', 'laravel_session', 'csrf-token'] },
    { name: 'Ruby on Rails', patterns: ['data-turbolinks', 'csrf-token', 'rails-ujs'] },
    { name: 'Django', patterns: ['csrfmiddlewaretoken', 'django'] },
    { name: 'Flask', patterns: ['flask'] },
    { name: 'Express', patterns: ['express', 'x-powered-by:express'] },
    { name: 'Bootstrap', patterns: ['bootstrap', 'cdn.jsdelivr.net/npm/bootstrap'] },
    { name: 'Tailwind CSS', patterns: ['tailwindcss', 'tailwind'] },
    { name: 'Material UI', patterns: ['material-ui', 'mui'] },
    { name: 'Chakra UI', patterns: ['chakra-ui', 'chakra'] },
    { name: 'Alpine.js', patterns: ['x-data', 'x-init', 'x-on:', 'alpine'] },
    { name: 'HTMX', patterns: ['hx-get', 'hx-post', 'htmx'] },
    { name: 'Stimulus', patterns: ['data-controller', 'stimulus'] },
    { name: 'Turbo', patterns: ['data-turbo', 'turbo-frame'] },
    { name: 'Lit', patterns: ['lit-html', 'lit-element'] },
    { name: 'Preact', patterns: ['preact', '__preact'] },
    { name: 'Solid.js', patterns: ['solid-js', '_$HY'] },
    { name: 'Qwik', patterns: ['qwik', 'q:'] },
  ],

  // Analytics platforms
  ANALYTICS: [
    { name: 'Google Analytics', patterns: ['google-analytics.com', 'gtag(', 'ga.js', 'analytics.js', 'googletagmanager'] },
    { name: 'Google Tag Manager', patterns: ['googletagmanager.com', 'gtm.js'] },
    { name: 'Facebook Pixel', patterns: ['connect.facebook.net', 'fbevents.js', 'fbq('] },
    { name: 'Hotjar', patterns: ['hotjar', 'static.hotjar.com', 'hj('] },
    { name: 'Mixpanel', patterns: ['mixpanel', 'mixpanel.com'] },
    { name: 'Segment', patterns: ['segment.com', 'segment.io', 'analytics.js'] },
    { name: 'Amplitude', patterns: ['amplitude', 'amplitude.com'] },
    { name: 'Heap', patterns: ['heap', 'heapanalytics'] },
    { name: 'Plausible', patterns: ['plausible.io'] },
    { name: 'Matomo', patterns: ['matomo', 'piwik'] },
    { name: 'Clarity', patterns: ['clarity.ms', 'clarity('] },
    { name: 'Yandex Metrica', patterns: ['mc.yandex', 'metrika', 'ym('] },
    { name: 'FullStory', patterns: ['fullstory', 'fs.js'] },
    { name: 'Lucky Orange', patterns: ['luckyorange'] },
    { name: 'Crazy Egg', patterns: ['crazyegg'] },
    { name: 'Mouseflow', patterns: ['mouseflow'] },
    { name: 'PostHog', patterns: ['posthog'] },
  ],

  // Advertising platforms
  ADVERTISING: [
    { name: 'Google Ads', patterns: ['googleads', 'googlesyndication', 'googleadservices', 'adsbygoogle'] },
    { name: 'Facebook Ads', patterns: ['facebook.com/tr', 'fbq('] },
    { name: 'LinkedIn Ads', patterns: ['linkedin.com/px', 'snap.licdn.com'] },
    { name: 'Twitter Ads', patterns: ['static.ads-twitter.com', 'twq('] },
    { name: 'TikTok Ads', patterns: ['analytics.tiktok.com', 'ttq('] },
    { name: 'Amazon Ads', patterns: ['amazon-adsystem', 'amzn'] },
    { name: 'AdRoll', patterns: ['adroll', 'd.adroll.com'] },
    { name: 'Criteo', patterns: ['criteo'] },
    { name: 'Taboola', patterns: ['taboola'] },
    { name: 'Outbrain', patterns: ['outbrain'] },
    { name: 'Media.net', patterns: ['media.net'] },
    { name: 'PropellerAds', patterns: ['propellerads'] },
  ],

  // Social platform detection
  SOCIAL_PLATFORMS: [
    { name: 'Facebook', pattern: 'facebook.com' },
    { name: 'Twitter/X', pattern: 'twitter.com' },
    { name: 'X', pattern: 'x.com' },
    { name: 'LinkedIn', pattern: 'linkedin.com' },
    { name: 'Instagram', pattern: 'instagram.com' },
    { name: 'YouTube', pattern: 'youtube.com' },
    { name: 'TikTok', pattern: 'tiktok.com' },
    { name: 'Pinterest', pattern: 'pinterest.com' },
    { name: 'Telegram', pattern: 't.me' },
    { name: 'WhatsApp', pattern: 'wa.me' },
    { name: 'Discord', pattern: 'discord.gg' },
    { name: 'Reddit', pattern: 'reddit.com' },
    { name: 'GitHub', pattern: 'github.com' },
    { name: 'Dribbble', pattern: 'dribbble.com' },
    { name: 'Behance', pattern: 'behance.net' },
    { name: 'Twitch', pattern: 'twitch.tv' },
    { name: 'Snapchat', pattern: 'snapchat.com' },
    { name: 'Threads', pattern: 'threads.net' },
    { name: 'Mastodon', pattern: 'mastodon' },
    { name: 'Bluesky', pattern: 'bsky.app' },
    { name: 'Medium', pattern: 'medium.com' },
    { name: 'Substack', pattern: 'substack.com' },
  ],

  // Deprecated HTML elements
  DEPRECATED_ELEMENTS: [
    'acronym',
    'applet',
    'basefont',
    'bgsound',
    'big',
    'blink',
    'center',
    'content',
    'dir',
    'font',
    'frame',
    'frameset',
    'hgroup',
    'image',
    'isindex',
    'keygen',
    'listing',
    'marquee',
    'menuitem',
    'multicol',
    'nextid',
    'nobr',
    'noembed',
    'noframes',
    'plaintext',
    'rb',
    'rtc',
    'shadow',
    'spacer',
    'strike',
    'tt',
    'xmp',
  ],

  // ARIA roles list
  ARIA_ROLES: [
    'alert',
    'alertdialog',
    'application',
    'article',
    'banner',
    'button',
    'cell',
    'checkbox',
    'columnheader',
    'combobox',
    'complementary',
    'contentinfo',
    'definition',
    'dialog',
    'directory',
    'document',
    'feed',
    'figure',
    'form',
    'grid',
    'gridcell',
    'group',
    'heading',
    'img',
    'link',
    'list',
    'listbox',
    'listitem',
    'log',
    'main',
    'marquee',
    'math',
    'menu',
    'menubar',
    'menuitem',
    'menuitemcheckbox',
    'menuitemradio',
    'navigation',
    'none',
    'note',
    'option',
    'presentation',
    'progressbar',
    'radio',
    'radiogroup',
    'region',
    'row',
    'rowgroup',
    'rowheader',
    'scrollbar',
    'search',
    'searchbox',
    'separator',
    'slider',
    'spinbutton',
    'status',
    'switch',
    'tab',
    'table',
    'tablist',
    'tabpanel',
    'term',
    'textbox',
    'timer',
    'toolbar',
    'tooltip',
    'tree',
    'treegrid',
    'treeitem',
  ],

  // Schema.org required fields by type
  SCHEMA_REQUIREMENTS: {
    Product: {
      required: ['name', 'image'],
      recommended: ['description', 'offers', 'review', 'aggregateRating', 'brand', 'sku', 'gtin'],
      needsOneOf: ['offers', 'review', 'aggregateRating'],
    },
    Article: {
      required: ['headline', 'datePublished', 'author'],
      recommended: ['image', 'dateModified', 'publisher', 'description'],
    },
    BlogPosting: {
      required: ['headline', 'datePublished', 'author'],
      recommended: ['image', 'dateModified', 'publisher', 'description'],
    },
    NewsArticle: {
      required: ['headline', 'datePublished', 'author', 'dateModified'],
      recommended: ['image', 'publisher', 'description'],
    },
    Organization: {
      required: ['name'],
      recommended: ['url', 'logo', 'contactPoint', 'sameAs', 'address'],
    },
    LocalBusiness: {
      required: ['name', 'address'],
      recommended: ['telephone', 'url', 'openingHours', 'image', 'priceRange', 'geo'],
    },
    FAQPage: {
      required: ['mainEntity'],
    },
    BreadcrumbList: {
      required: ['itemListElement'],
    },
    WebSite: {
      recommended: ['name', 'url', 'potentialAction'],
    },
    Person: {
      required: ['name'],
      recommended: ['url', 'image', 'jobTitle', 'sameAs'],
    },
    Event: {
      required: ['name', 'startDate', 'location'],
      recommended: ['endDate', 'description', 'image', 'offers', 'performer', 'organizer'],
    },
    Recipe: {
      required: ['name', 'image'],
      recommended: ['author', 'datePublished', 'description', 'recipeIngredient', 'recipeInstructions', 'nutrition'],
    },
    Review: {
      required: ['itemReviewed', 'author'],
      recommended: ['reviewRating', 'datePublished', 'reviewBody'],
    },
    VideoObject: {
      required: ['name', 'description', 'thumbnailUrl', 'uploadDate'],
      recommended: ['duration', 'contentUrl', 'embedUrl', 'interactionStatistic'],
    },
    HowTo: {
      required: ['name', 'step'],
      recommended: ['description', 'image', 'totalTime', 'supply', 'tool'],
    },
    Course: {
      required: ['name', 'provider'],
      recommended: ['description', 'offers', 'hasCourseInstance'],
    },
    JobPosting: {
      required: ['title', 'description', 'datePosted', 'hiringOrganization', 'jobLocation'],
      recommended: ['employmentType', 'baseSalary', 'validThrough'],
    },
    SoftwareApplication: {
      required: ['name'],
      recommended: ['offers', 'operatingSystem', 'applicationCategory', 'aggregateRating'],
    },
  } as Record<string, { required?: string[]; recommended?: string[]; needsOneOf?: string[] }>,

  // Valid ISO 639-1 language codes
  VALID_LANG_CODES: [
    'aa', 'ab', 'ae', 'af', 'ak', 'am', 'an', 'ar', 'as', 'av', 'ay', 'az',
    'ba', 'be', 'bg', 'bh', 'bi', 'bm', 'bn', 'bo', 'br', 'bs',
    'ca', 'ce', 'ch', 'co', 'cr', 'cs', 'cu', 'cv', 'cy',
    'da', 'de', 'dv', 'dz',
    'ee', 'el', 'en', 'eo', 'es', 'et', 'eu',
    'fa', 'ff', 'fi', 'fj', 'fo', 'fr', 'fy',
    'ga', 'gd', 'gl', 'gn', 'gu', 'gv',
    'ha', 'he', 'hi', 'ho', 'hr', 'ht', 'hu', 'hy', 'hz',
    'ia', 'id', 'ie', 'ig', 'ii', 'ik', 'io', 'is', 'it', 'iu',
    'ja', 'jv',
    'ka', 'kg', 'ki', 'kj', 'kk', 'kl', 'km', 'kn', 'ko', 'kr', 'ks', 'ku', 'kv', 'kw', 'ky',
    'la', 'lb', 'lg', 'li', 'ln', 'lo', 'lt', 'lu', 'lv',
    'mg', 'mh', 'mi', 'mk', 'ml', 'mn', 'mr', 'ms', 'mt', 'my',
    'na', 'nb', 'nd', 'ne', 'ng', 'nl', 'nn', 'no', 'nr', 'nv', 'ny',
    'oc', 'oj', 'om', 'or', 'os',
    'pa', 'pi', 'pl', 'ps', 'pt',
    'qu',
    'rm', 'rn', 'ro', 'ru', 'rw',
    'sa', 'sc', 'sd', 'se', 'sg', 'si', 'sk', 'sl', 'sm', 'sn', 'so', 'sq', 'sr', 'ss', 'st', 'su', 'sv', 'sw',
    'ta', 'te', 'tg', 'th', 'ti', 'tk', 'tl', 'tn', 'to', 'tr', 'ts', 'tt', 'tw', 'ty',
    'ug', 'uk', 'ur', 'uz',
    've', 'vi', 'vo',
    'wa', 'wo',
    'xh',
    'yi', 'yo',
    'za', 'zh', 'zu',
  ],

  // Common stop words for keyword density
  STOP_WORDS: new Set([
    'a', 'an', 'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of',
    'with', 'by', 'from', 'up', 'about', 'into', 'through', 'during', 'before',
    'after', 'above', 'below', 'between', 'under', 'again', 'further', 'then',
    'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'each',
    'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only',
    'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just',
    'don', 'should', 'now', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'would', 'could',
    'should', 'might', 'must', 'shall', 'it', 'its', 'this', 'that', 'these', 'those',
    'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours',
    'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers',
    'herself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who',
    'whom', 'if', 'as',
  ]),

  // Trust signals patterns
  TRUST_PATTERNS: {
    terms: ['/terms', '/tos', '/terms-of-service', '/terms-and-conditions', '/პირობები'],
    cookie: ['/cookie', '/cookies', '/cookie-policy', '/ქუქი'],
    ssl: ['ssl', 'secure', 'https', 'encrypted', 'protected'],
    payment: ['visa', 'mastercard', 'paypal', 'stripe', 'amex', 'apple pay', 'google pay'],
    review: ['trustpilot', 'reviews', 'testimonials', 'rating', 'stars', 'გამოხმაურება'],
    certification: ['certified', 'accredited', 'verified', 'iso', 'gdpr', 'hipaa', 'pci'],
  },
};
